In [2]:
import pathlib
from collections import OrderedDict
from typing import Any, Iterable

import ray
import numpy as np
import anndata
import pandas as pd
# from bolero.tl.dataset.sc_transforms import FilterRegions
# from bolero.tl.dataset.transforms import (
#     FetchRegionOneHot,
#     ReverseComplement,
# )

# from bolero.utils import get_global_coords, understand_regions
# from bolero.tl.dataset.file_transforms import FetchRegionBigWigs, GetEmbedding
# from utils import BorzoiRegions, clamp_sqrt_large_value

# DNA_NAME = "dna_one_hot"
from bolero.tl.model.borzoi.dataset import BorzoiDatasetOnline
from bolero import init

init(num_cpus=32, object_store_memory_gb=100)

2024-10-24 14:08:31,655	INFO worker.py:1762 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265

In [3]:
data_dir = '/large_storage/zhoulab/tlgallent/data/Li2023Science/'
bw_file_path = f'{data_dir}bigwig/'
cell_types = ['ASC', 'Vip', 'L5_IT']
# cell_types = ['ASC']
# bed = f'{data_dir}peaks/cCREs.bed'

In [4]:
bigwig_paths = [f'{bw_file_path}'+f'{ct}.bw' for ct in cell_types]
bigwig_paths

['/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/ASC.bw',
 '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/Vip.bw',
 '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/L5_IT.bw']

In [5]:
bigwig_names_dict = OrderedDict()
for path in bigwig_paths:
    bigwig_names_dict[pathlib.Path(path).name.rsplit('.',1)[0]] = path


assert len(bigwig_names_dict) == len(bigwig_paths)

In [6]:
for i, x in enumerate(bigwig_names_dict):
    print(i, x)
    print(bigwig_names_dict[x])

0 ASC
/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/ASC.bw
1 Vip
/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/Vip.bw
2 L5_IT
/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/L5_IT.bw

In [7]:
bigwig_paths_dict = OrderedDict()

In [8]:
for path in bigwig_paths:
    cell_type = path.split('/')[-1]
    cell_type = cell_type.rsplit('.',1)[0]
    bigwig_paths_dict[cell_type] = path

In [9]:
path = "/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/ASC.bw"

# Remove the leading and trailing quotes
# path = path.strip("'")

# Split the path and get the last part
filename_with_extension = path.split('/')[-1]

# Remove the extension
filename_without_extension = filename_with_extension.rsplit('.', 1)[0]

filename_without_extension

'ASC'

In [10]:
adata = anndata.read_h5ad('/large_storage/zhoulab/tlgallent/data/cell_29000_rna_raw_gencode_adata_with_embeddings.h5ad')
scvi_embedding = adata.obsm['X_scVI']
# Create a DataFrame with embeddings and cell types
df = pd.DataFrame(scvi_embedding, index=adata.obs.index)
df['cell_type'] = adata.obs['MajorType']
# Group by cell type
grouped = df.groupby('cell_type').mean()
# Get embedding
recalculated_embedding = grouped.to_numpy()


leg_map = {item: index for index, item in enumerate(grouped.index.to_list())}
leg_map

/tmp/ipykernel_437424/135511446.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df.groupby('cell_type').mean()

{'ASC': 0,
 'Amy': 1,
 'CHD7': 2,
 'EC': 3,
 'Foxp2': 4,
 'L4_IT': 5,
 'L5_ET': 6,
 'L5_IT': 7,
 'L6_CT': 8,
 'L6_IT': 9,
 'L6_IT_Car3': 10,
 'L6b': 11,
 'L23_IT': 12,
 'L56_NP': 13,
 'Lamp5': 14,
 'Lamp5_LHX6': 15,
 'MGC': 16,
 'MSN_D1': 17,
 'MSN_D2': 18,
 'ODC': 19,
 'OPC': 20,
 'PC': 21,
 'Pvalb': 22,
 'Pvalb_ChC': 23,
 'Sncg': 24,
 'Sst': 25,
 'SubCtx': 26,
 'VLMC': 27,
 'Vip': 28}

In [11]:
for x in cell_types: print(recalculated_embedding[leg_map[x]])

[ 8.1639951e-01 -1.8141804e-02  1.9753073e-01 -7.8901976e-02
 -4.7131974e-02  3.6194551e-01  4.6953613e-01 -5.1410848e-01
  3.9528120e-01  3.6116695e-01  3.5134324e-01 -3.3298790e-01
  8.2313013e-01 -1.3897213e-04 -2.4195077e-01 -1.2614359e+00
 -1.4791901e-02  8.7709546e-01 -5.9044462e-01  5.2708077e-01
  1.1471124e+00  7.0392508e-03  8.5427901e-03  1.2751074e+00
 -9.8622002e-02 -1.2545434e-02 -1.3628805e-01  3.1145185e-01
  8.4211981e-01 -3.4372029e-01  2.4858487e-01 -2.3774694e-01
 -1.6763769e+00 -3.4681487e-01 -4.7062245e-01  6.3714623e-01
  2.5193891e-01  1.8790249e+00  1.5217294e+00  3.6817715e-01
 -1.1824822e+00  3.0063364e-01 -3.6512426e-01  4.6925202e-01
 -6.6868114e-01  2.3944591e-01  9.7631979e-01 -4.0132409e-01
  4.8463538e-01  6.4016777e-01]
[-6.93263650e-01  2.43766513e-02  5.12231112e-01 -1.10374182e-01
  3.21036965e-01  4.99607325e-02 -5.97075462e-01  5.64686716e-01
 -1.59261763e-01 -2.85740286e-01  2.75409430e-01  6.66004956e-01
  2.10795522e-01  1.94720123e-02 -6.71250075e-02 -1.64004803e-01
  9.96721257e-03 -1.09355569e+00 -5.46239674e-01 -1.32769001e+00
  7.53668919e-02  1.82698160e-01  2.44858162e-03 -5.26640773e-01
 -1.22950518e+00  2.46721786e-04 -1.04143226e+00 -2.04258174e-01
  2.92661816e-01 -8.85525048e-01  1.16283394e-01  1.73489943e-01
 -4.59580161e-02 -1.24140120e+00  9.60942328e-01  8.29250365e-02
 -7.54813731e-01  1.09322166e+00  9.47222769e-01  2.98765451e-01
  4.44557697e-01 -1.96307480e-01  4.77931798e-02  5.65452337e-01
  3.53935361e-01 -9.16834474e-01 -6.77163005e-01 -8.12925816e-01
  2.14365050e-01 -6.25990391e-01]
[-0.5761479   0.03741751 -0.45102638 -0.11324705  0.17379826 -0.13753225
  0.8272898  -0.5802351  -0.23396446 -0.7528173   0.46749586 -0.17817563
 -0.16687073  0.00938179  0.45087373 -0.06413791 -0.02013126  0.20074025
 -0.14203735  0.04376414  0.6146851  -0.14206989 -0.00317902 -0.24536698
 -0.5326252  -0.00588112  1.2102584  -0.7616567  -1.035038   -0.28327492
  0.40419528 -0.11168538 -0.19188108  0.03604767  0.70417535 -0.22855254
 -0.36033776  0.4930149  -0.6005642   0.43848255  1.6228884  -0.6147382
 -0.29257303  0.23380303 -0.08716812  0.21963704  0.78487146 -0.3758804
  0.11584551 -1.1753058 ]

In [12]:
# borzoi_online_dataset = BorzoiDatasetOnline(bigwig_paths=bigwig_paths, bed=bed, leg_map=leg_map, genome="hg38")

In [13]:
# borzoi_online_dataset.train()

In [14]:
# borzoi_online_dataset.get_default_config()

In [15]:
# vars(borzoi_online_dataset)

In [16]:
# loader1 = borzoi_online_dataset.get_dataloader(folds=0, region_bed=bed)

# for batch in loader1:
#     pass

# for k, v in batch.items():
#     print(k, v.dtype, v.shape)
# del loader1

In [17]:
# leg_map['ASC'] = 1841
leg_map

{'ASC': 0,
 'Amy': 1,
 'CHD7': 2,
 'EC': 3,
 'Foxp2': 4,
 'L4_IT': 5,
 'L5_ET': 6,
 'L5_IT': 7,
 'L6_CT': 8,
 'L6_IT': 9,
 'L6_IT_Car3': 10,
 'L6b': 11,
 'L23_IT': 12,
 'L56_NP': 13,
 'Lamp5': 14,
 'Lamp5_LHX6': 15,
 'MGC': 16,
 'MSN_D1': 17,
 'MSN_D2': 18,
 'ODC': 19,
 'OPC': 20,
 'PC': 21,
 'Pvalb': 22,
 'Pvalb_ChC': 23,
 'Sncg': 24,
 'Sst': 25,
 'SubCtx': 26,
 'VLMC': 27,
 'Vip': 28}

## PROCESSED DATA ##

In [18]:
borzoi_online_dataset = BorzoiDatasetOnline(bigwig_paths=bigwig_paths, embeddings_path='/large_storage/zhoulab/tlgallent/data/cell_29000_rna_raw_gencode_adata_with_embeddings.h5ad', bed=None, genome="hg38", use_borzoi_regions=True)
borzoi_online_dataset.train()

/home/tlgallent/projects/software/bolero/src/bolero/tl/model/borzoi/dataset.py:494: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df.groupby('cell_type').mean()

In [19]:
borzoi_online_dataset.get_default_config()

{'bigwig_paths': 'REQUIRED',
 'bed': 'REQUIRED',
 'embeddings_path': 'REQUIRED',
 'lora': 'REQUIRED',
 'genome': 'hg38',
 'batch_size': 2,
 'dna_window': 524288,
 'pos_resolution': 32,
 'reverse_complement': True,
 'max_jitter': 0,
 'clamp_sqrt_threshold': None,
 'shuffle_files': True,
 'use_borzoi_regions': True}

In [20]:
borzoi_online_dataset.lora

bool

In [21]:
vars(borzoi_online_dataset)

{'genome': Genome: hg38
 Fasta Path: /home/tlgallent/projects/software/bolero/src/bolero/data/hg38/fasta/hg38.fa
 Genome One Hot Zarr: Not created,
 'batch_size': 2,
 'dna': False,
 '_block_size': 20,
 '_max_blocks': 200,
 'bigwig_paths': ['/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/ASC.bw',
  '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/Vip.bw',
  '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/L5_IT.bw'],
 'bigwig_names_dict': OrderedDict([('ASC',
               '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/ASC.bw'),
              ('Vip',
               '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/Vip.bw'),
              ('L5_IT',
               '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/L5_IT.bw')]),
 'bigwig_id_dict': OrderedDict([('ASC', 0), ('Vip', 1), ('L5_IT', 2)]),
 'embeddings_path': '/large_storage/zhoulab/tlgallent/data/cell_29000_rna_raw_gencode_adata_with_embeddings.h5ad',
 'leg_map': {'ASC': array([ 8.1639951e-01, -1.8141804e-02,  1.9753073e-01, -7.8901976e-02,
         -4.7131974e-02,  3.6194551e-01,  4.6953613e-01, -5.1410848e-01,
          3.9528120e-01,  3.6116695e-01,  3.5134324e-01, -3.3298790e-01,
          8.2313013e-01, -1.3897213e-04, -2.4195077e-01, -1.2614359e+00,
         -1.4791901e-02,  8.7709546e-01, -5.9044462e-01,  5.2708077e-01,
          1.1471124e+00,  7.0392508e-03,  8.5427901e-03,  1.2751074e+00,
         -9.8622002e-02, -1.2545434e-02, -1.3628805e-01,  3.1145185e-01,
          8.4211981e-01, -3.4372029e-01,  2.4858487e-01, -2.3774694e-01,
         -1.6763769e+00, -3.4681487e-01, -4.7062245e-01,  6.3714623e-01,
          2.5193891e-01,  1.8790249e+00,  1.5217294e+00,  3.6817715e-01,
         -1.1824822e+00,  3.0063364e-01, -3.6512426e-01,  4.6925202e-01,
         -6.6868114e-01,  2.3944591e-01,  9.7631979e-01, -4.0132409e-01,
          4.8463538e-01,  6.4016777e-01], dtype=float32),
  'Amy': array([-0.2618679 ,  0.04501783,  0.43473333, -0.0628459 ,  0.24931408,
         -0.05374489,  0.193142  ,  0.5291383 , -1.4193636 ,  0.25473294,
          1.2108593 , -0.72796243, -0.41200545, -0.00727793,  0.4727533 ,
          0.52395695, -0.02993242,  0.31014   , -1.0017425 , -0.48748592,
          1.3848633 ,  1.169399  , -0.03216521, -0.36451647,  0.23009963,
          0.00216777,  0.43319446, -0.92981625,  1.2704101 ,  0.49261138,
          0.24372788,  0.55863273,  0.575894  ,  0.9810025 , -0.85199624,
          0.865773  , -0.6481909 ,  0.33687416, -0.16402279, -0.6171484 ,
          0.58828974, -0.3879527 , -0.37635645, -0.18228385,  0.03101816,
          0.16246337, -0.3579599 , -1.0377922 , -0.03406337, -0.35506967],
        dtype=float32),
  'CHD7': array([-7.4888158e-01,  4.9944401e-02, -4.7796547e-01, -2.6367178e-02,
          2.9334119e-01,  4.8583391e-01, -9.1393220e-01,  2.7906230e-01,
          1.0617260e-01, -7.5484997e-01,  2.4566789e-01,  2.6664144e-01,
         -4.0341055e-01,  2.8930619e-02, -3.0289319e-01, -5.3901829e-02,
         -1.7365271e-02, -1.2227482e+00,  3.4285814e-01, -4.0957341e-01,
         -1.7411034e-01, -2.2163592e-02,  8.7906740e-04, -5.2817619e-01,
         -1.2973790e+00, -7.7110524e-03, -6.9025463e-01,  1.7185730e+00,
          6.2267059e-01, -1.4256647e+00, -1.7223687e-01,  6.4476281e-01,
          7.4809438e-01, -8.4336931e-01, -2.6844811e-01,  2.0234360e-01,
         -7.4113719e-02, -9.5511341e-01,  9.3807399e-01,  1.7870782e-01,
          2.6299527e-01,  8.0883443e-01,  3.4187871e-01,  1.9190857e-01,
          3.9324518e-02, -2.4051075e-01, -1.3896073e-01, -2.7743664e-01,
          4.0857381e-01, -4.3554026e-01], dtype=float32),
  'EC': array([ 6.5144145e-01, -4.2244658e-02, -1.0154675e-01, -1.4585440e-02,
         -2.4178135e-01, -1.2776625e-01,  5.2036035e-01, -1.0883596e+00,
         -7.5636590e-01, -7.4420303e-02, -4.8188936e-02, -1.4764805e-01,
         -6.2821257e-01, -6.6921376e-03,  4.5330706e-01, -1.6794899e+00,
          9.3075621e-04,  1.9325505e-01,  5.8671361e-01,  1.2941933e+00,
         -3.2050547e-01,  3.1837520e-01, -5.2532912e-03, -6.9588286e-01,
          5.4125386e-01, -2.1306569e-02,  3.5869190e-01, -4.7614810e-01,
         -2.0249512e+00,  1.0516165e+00,  5.5762321e-02,  4.9886342e-02,
          5.1577061e-01, -2.2123478e-01, -3.1697604e-01,  1.5344200e-01,
         -4.4804823e-01,  7.1356654e-02,  5.6395268e-01,  4.4346604e-02,
         -8.8336951e-01,  7.3286027e-01, -2.9831143e-02,  4.4731554e-01,
          3.0319509e-01,  6.5402228e-01,  1.2175227e+00, -7.5119984e-01,
          3.7087908e-01,  1.7460146e+00], dtype=float32),
  'Foxp2': array([ 0.3074768 ,  0.00590024,  0.88294107, -0.04131758, -0.13624375,
         -0.6366578 ,  0.10524572, -0.2438991 , -0.51908123,  1.4348586 ,
          1.2453492 , -0.02409108,  0.9025278 , -0.0022508 , -0.6484414 ,
          0.0944866 , -0.00536915,  0.06672862, -0.21813947,  1.2796766 ,
          0.7864109 ,  0.4068921 , -0.0245533 ,  0.12048028,  0.05671712,
         -0.01188553,  0.11410934,  1.0464587 ,  1.4917186 ,  0.6454572 ,
          0.18919738, -1.0317836 ,  0.5801891 ,  0.23036097, -0.14732915,
         -0.03282807,  0.6610329 , -1.6142842 , -0.60188   , -0.36060306,
         -0.49189845, -0.08496428, -0.18852475,  0.8781379 ,  0.48322314,
          0.03722635, -1.2008904 ,  0.9766891 ,  1.0743034 ,  0.31566495],
        dtype=float32),
  'L4_IT': array([ 0.2958147 ,  0.02284165, -0.38839325, -0.09664876,  0.10661154,
          0.22284563,  0.79701924, -0.19192746,  0.2104479 ,  0.03370341,
          0.04184983,  0.33037138, -0.15790303,  0.02123803, -0.29754078,
          0.37600306, -0.02448654, -0.2810502 , -0.5988892 ,  0.6927685 ,
          0.4955096 ,  0.06006113, -0.00698851, -0.223055  , -0.18377246,
          0.00213948,  0.54270357, -1.9013454 , -1.0468235 , -1.3418341 ,
          0.1327133 ,  0.04398237,  0.45825616, -0.19276579,  0.36323825,
         -0.32694104,  0.4016874 ,  0.13096726,  0.16687946,  0.14212546,
          0.91225797, -0.84349465,  0.04995179, -0.06300876,  0.32298908,
          1.0589393 ,  0.6060053 ,  0.2032628 ,  0.76779115, -0.5694304 ],
        dtype=float32),
  'L5_ET': array([ 1.78503022e-01,  4.20565046e-02, -2.76771784e-01,  1.21085666e-01,
          3.69155794e-01, -4.66612428e-01,  8.72340560e-01,  1.64469075e-03,
          8.21766913e-01, -1.07497203e+00, -4.71557051e-01,  6.18944643e-04,
         -5.11861682e-01,  2.38733999e-02,  1.81650206e-01,  9.38483179e-02,
         -1.08680995e-02,  7.32670724e-01,  7.56673157e-01,  3.59730095e-01,
         -8.18078160e-01,  1.00132692e+00, -1.61969736e-02, -4.84234273e-01,
         -9.59313989e-01,  1.14598852e-02,  1.17329679e-01,  1.19935751e+00,
          4.62772138e-02,  5.01354396e-01,  9.95633230e-02,  4.93783683e-01,
          9.96473312e-01,  1.06855059e+00, -3.26810569e-01,  4.37479280e-02,
         -5.42352498e-01, -5.64491414e-02, -3.36388409e-01, -7.23691821e-01,
          7.14131653e-01, -1.26472390e+00, -3.50912631e-01, -5.74449360e-01,
         -7.11424127e-02, -9.23121572e-01,  9.60731745e-01, -7.85519481e-01,
         -3.97503793e-01, -1.55838134e-04], dtype=float32),
  'L5_IT': array([-0.5761479 ,  0.03741751, -0.45102638, -0.11324705,  0.17379826,
         -0.13753225,  0.8272898 , -0.5802351 , -0.23396446, -0.7528173 ,
          0.46749586, -0.17817563, -0.16687073,  0.00938179,  0.45087373,
         -0.06413791, -0.02013126,  0.20074025, -0.14203735,  0.04376414,
          0.6146851 , -0.14206989, -0.00317902, -0.24536698, -0.5326252 ,
         -0.00588112,  1.2102584 , -0.7616567 , -1.035038  , -0.28327492,
          0.40419528, -0.11168538, -0.19188108,  0.03604767,  0.70417535,
         -0.22855254, -0.36033776,  0.4930149 , -0.6005642 ,  0.43848255,
          1.6228884 , -0.6147382 , -0.29257303,  0.23380303, -0.08716812,
          0.21963704,  0.78487146, -0.3758804 ,  0.11584551, -1.1753058 ],
        dtype=float32),
  'L6_CT': array([ 3.5445441e-02,  2.0706924e-02,  1.5160106e-01, -2.9261272e-02,
         -4.0842110e-01, -2.1069746e-02,  1.1957140e+00, -1.0999700e+00,
         -3.0858977e-02,  6.5321451e-01,  4.8539111e-01, -6.6691244e-01,
          2.1231686e-01,  3.8209318e-03,  7.3381644e-01,  5.8813083e-01,
          4.2090702e-04,  3.5764414e-01, -1.1908000e+00, -4.6384219e-02,
         -4.7493455e-01,  3.6899041e-02, -1.7195694e-02, -8.4604606e-02,
         -1.1875256e+00,  9.4057685e-03,  9.6888071e-01,  3.7289843e-01,
         -4.0866622e-01,  1.4397677e+00,  8.6534031e-02,  2.6680222e-01,
          2.5035450e-01,  9.8353928e-01,  8.1945479e-01,  3.6195061e-01,
         -1.6036056e-02, -3.9636856e-01,  2.0962473e-02, -2.9151136e-01,
          6.1081505e-01,  1.9967476e-01,  3.2208076e-01, -5.2057978e-02,
          3.4278497e-01, -1.3705396e-02,  1.1069098e-01,  6.5389311e-01,
         -7.6460928e-01,  2.9070154e-01], dtype=float32),
  'L6_IT': array([-0.24610396, -0.01785916, -0.1028038 ,  0.12709941, -0.09587981,
          0.5269487 ,  1.364086  ,  0.5895718 , -0.0913228 ,  0.04064352,
          0.04718557,  0.3754359 ,  0.5494818 ,  0.00985377, -0.04015518,
          0.26471382, -0.02381022, -0.3836552 , -0.7536001 , -0.79343784,
         -0.09893016,  0.10333041, -0.02772301, -0.5923624 , -0.7807652 ,
          0.03510411,  1.4698303 , -0.9381963 , -0.15204051,  0.16290322,
         -0.61244196, -0.22655071, -0.182305  ,  0.6732459 , -0.4361442 ,
         -0.17466684,  0.3744914 ,  0.25926122, -0.718504  ,  0.8122953 ,
          1.025513  , -0.11565936,  0.05988207, -0.4171779 ,  0.6505022 ,
         -0.55592245,  1.0166606 , -0.49420446, -0.42070106,  0.04246509],
        dtype=float32),
  'L6_IT_Car3': array([ 0.15078746,  0.02705513, -0.5360983 , -0.07241212, -0.98304117,
          1.0355841 ,  0.7088702 ,  0.60911965, -0.29054326,  0.5004194 ,
          0.287696  , -0.13663436,  1.2851173 ,  0.00580689,  0.13521728,
          0.7015499 , -0.0340593 ,  0.04261491, -0.11298363, -1.235364  ,
         -0.50087816,  0.11685476, -0.02229976, -1.1600759 ,  0.229267  ,
          0.03482633,  0.5861967 , -0.62895876,  0.5737985 , -0.5167159 ,
         -0.30101702,  0.48515904,  0.21370465, -0.05253629, -1.4797051 ,
         -0.8994333 , -0.17674743,  0.7174404 ,  0.5604234 ,  0.07773702,
          0.10015114,  0.46252012, -0.43260264, -0.51296836,  1.3125739 ,
          0.938289  ,  0.33680078,  0.9908265 , -0.12358619, -0.34127277],
        dtype=float32),
  'L6b': array([-0.73984283,  0.06718863, -1.2566729 ,  0.08754751, -0.851024  ,
          0.61466014,  1.0083088 , -0.42266718,  0.02721727,  0.07964221,
         -0.22542202, -0.316299  ,  1.5380684 ,  0.01879747,  0.31714657,
         -0.554765  , -0.0165906 ,  0.2832321 , -0.11088851, -0.61062956,
         -0.74452686,  0.23858237, -0.02166655, -0.42376384, -0.9336412 ,
         -0.00155801, -0.3571541 ,  0.7049318 ,  0.23220743,  0.78185993,
          0.07991429, -0.7871324 , -0.24338613,  0.4067364 ,  1.4052713 ,
         -0.6048808 , -0.36720884,  0.46955392, -0.557397  ,  0.00690812,
          0.93522197, -0.2282853 ,  0.4178691 , -0.22783801,  0.8967074 ,
         -0.31989354,  0.04488577,  1.1863468 , -0.5639171 , -0.6026958 ],
        dtype=float32),
  'L23_IT': array([ 0.26462844, -0.02033748,  0.14455268,  0.01837485,  0.12427693,
         -0.22775848,  0.9674499 ,  0.5675109 ,  0.5574221 , -0.44705597,
         -0.331732  , -0.10828251,  0.39366013,  0.00788833, -0.42535353,
          0.24984679, -0.0143854 , -0.9253872 , -0.42005104,  0.42591074,
          0.03975768,  1.1815794 , -0.02348916, -0.08779372,  0.13583755,
          0.01029261,  0.51402014, -1.4392987 , -0.4644374 ,  0.24106106,
         -0.11781739, -0.04084233,  0.8262865 ,  0.49622348, -1.1220819 ,
         -0.25801957,  0.05772907,  0.5191488 ,  0.06123424, -0.34654883,
          0.621349  , -1.1053675 ,  0.21141832, -0.19744694,  0.23696586,
          0.28153464, -0.05810937, -1.0058448 , -0.35011134, -0.55235803],
        dtype=float32),
  'L56_NP': array([ 0.02884304,  0.00207882,  0.151553  ,  0.12493754,  0.1400772 ,
          0.6989194 , -0.06461968, -1.3992786 ,  0.6846762 ,  0.866466  ,
          0.36431333, -0.11534069,  0.05428935, -0.00738202,  0.75013566,
          0.48532045, -0.02320756,  0.675702  ,  0.41094077,  0.05774179,
         -0.7121509 ,  0.8559307 ,  0.00947048,  0.43313965, -0.5489287 ,
         -0.01903447,  0.9157707 ,  0.05030588, -1.269635  , -1.172168  ,
          0.23414256,  0.91599184,  0.2524879 ,  0.4850074 ,  1.3669513 ,
          0.32373908, -0.37293392, -0.94718814,  0.59165287,  0.09718224,
         -0.49309507, -0.18353269, -0.08647388,  0.269679  ,  0.06902532,
          0.49382815, -0.00305786,  1.3096232 , -0.42917424, -0.9805138 ],
        dtype=float32),
  'Lamp5': array([ 0.11265901,  0.05045281, -0.2528157 , -0.10440061,  0.39592877,
          0.35629353, -0.39598334,  1.2326704 ,  0.74549186, -0.7302881 ,
          0.8518393 ,  0.03098496,  0.60703695,  0.02633703, -0.5539303 ,
          0.66023207, -0.01328602, -0.54542744,  1.0053695 , -0.4828302 ,
         -0.15220651, -0.6171416 , -0.01259272, -0.01149915, -0.08418092,
         -0.00430663, -1.0851065 ,  0.35795355, -0.13802195,  0.08686599,
          0.06842344, -0.00676206,  0.31457666, -0.6908955 ,  0.81940526,
         -0.36274624,  0.22217496,  0.24824786, -0.44431213, -0.19354917,
         -0.08109083, -0.97961915, -0.00202535,  0.3215172 , -0.7108962 ,
         -0.6122716 , -1.018914  ,  0.53777397, -0.9810566 ,  0.85347027],
        dtype=float32),
  'Lamp5_LHX6': array([ 0.74107915,  0.03321569,  0.02945248,  0.02086602,  0.56709737,
         -0.05636505, -0.39633834,  0.7144895 , -0.6685152 , -0.9650221 ,
          0.9060242 ,  0.05686213, -0.3669371 ,  0.00643709, -0.40762216,
          1.1773831 , -0.0136151 , -0.09742299,  0.9940617 , -0.2857767 ,
         -0.02134258, -1.1471093 , -0.00405056,  0.65097654,  0.10731391,
         -0.0114856 , -0.00218957,  1.2130065 , -0.20086578,  0.5708226 ,
          0.18413529, -0.19502813,  1.0135405 , -0.5224264 ,  0.15803196,
         -0.44012105,  0.46920225, -1.0223624 , -0.69134545, -0.07795364,
         -0.6759693 , -0.42689437,  0.06311698,  0.4700873 , -0.3886718 ,
         -0.935172  , -1.0120167 , -0.18963696, -0.46242753,  0.49344584],
        dtype=float32),
  'MGC': array([-5.7360822e-01,  1.2939399e-02, -3.9362583e-01,  3.3726830e-02,
         -7.8589582e-01,  3.2554489e-01, -8.3368695e-01, -1.5742396e-01,
         -9.4115478e-01, -1.1601913e+00, -8.5726762e-01,  4.6182469e-01,
          5.7137567e-01,  1.6272308e-02,  8.8571377e-02, -1.6903092e+00,
         -1.1174137e-02,  8.7033856e-01, -1.7382436e-01,  5.9840310e-01,
         -8.7382507e-01,  2.7444997e-01, -2.5807405e-02, -3.0577477e-02,
          9.2145747e-01, -1.6862046e-03, -9.3424082e-01, -2.7364609e-01,
         -3.6088121e-01,  3.8256273e-01, -4.4810496e-02, -8.8268125e-01,
         -8.0513668e-01,  5.7555014e-01, -1.5458431e+00, -4.5465013e-01,
          5.2709991e-01, -8.8402557e-01,  2.2475339e-01, -3.1256187e-01,
         -8.4130305e-01,  1.3999267e+00,  5.1867619e-02,  7.4554779e-02,
         -6.4162898e-01,  4.5807478e-01,  1.1552010e+00,  1.1267008e+00,
         -1.2366370e-01,  3.1192759e-01], dtype=float32),
  'MSN_D1': array([ 4.9388519e-01,  2.5524430e-02, -7.6481909e-02, -7.0413582e-02,
         -5.3136819e-04, -1.8299939e-01, -3.9676002e-01,  9.7614169e-01,
          7.3254526e-01,  1.2815932e+00, -3.1836507e-01,  1.9914459e-01,
          4.3249339e-01,  3.3573762e-03,  5.3972486e-02,  2.7309871e-01,
         -2.5914749e-02,  3.0888230e-01,  1.7271575e-02,  1.3640002e+00,
         -4.1692337e-01,  2.3638348e-01, -3.0454159e-02, -1.0424547e-01,
          5.8427924e-01,  2.1603135e-02,  1.1682651e-01, -9.9802606e-02,
          1.5243185e+00, -5.8852953e-01,  1.2939838e-01, -1.7157903e-01,
         -4.0288672e-01,  5.8570325e-01, -1.6367301e+00,  1.2955582e-01,
         -9.4295092e-02, -1.0784528e+00, -8.1131935e-01, -7.1503088e-02,
          9.5824808e-02, -2.6446626e-01,  3.7312719e-01,  5.0225073e-01,
          5.2439111e-01, -3.0242625e-01, -1.7034136e-01, -2.7594239e-01,
         -2.8870147e-02,  5.2005172e-01], dtype=float32),
  'MSN_D2': array([-4.0772831e-01,  2.4930922e-02, -2.7516949e-01, -4.8947781e-03,
          2.6475263e-01,  6.7066228e-01, -3.9002070e-01,  8.1127322e-01,
          6.3731515e-01,  1.2197616e+00,  3.7853234e-02, -2.5713131e-01,
         -1.9646911e-01, -9.7560545e-04, -5.5521995e-02,  6.2005734e-01,
         -4.7835544e-02,  1.2896873e-02,  1.4020564e-01,  1.3940368e+00,
          1.8496532e-02, -1.0799998e-01, -2.0717368e-02, -1.0208328e+00,
          9.3243766e-01,  1.7554235e-02, -6.5074593e-02, -2.1007767e-02,
          1.0831369e+00,  3.6632493e-02,  2.7766272e-02, -4.8628041e-01,
         -6.0704458e-01,  4.9766144e-01, -2.1831486e+00,  4.5352358e-01,
         -2.9071650e-01, -1.1441855e+00, -3.2794079e-01,  7.7098079e-02,
          1.8684082e-01, -3.4442136e-01, -1.2740915e-01, -1.8475340e-01,
          7.2167295e-01, -4.2626271e-01, -9.6272513e-02,  2.1196146e-01,
          1.3714518e-01,  2.0759751e-01], dtype=float32),
  'ODC': array([ 4.89072859e-01,  1.50614316e-02, -3.32364328e-02, -2.99040116e-02,
          1.60789296e-01, -4.04815286e-01, -6.98750019e-01,  1.36825454e+00,
         -2.92209387e-01,  1.00418234e+00,  7.95950666e-02, -2.14275002e-01,
          7.97972023e-01,  8.74386076e-03, -5.36431253e-01,  1.10109195e-01,
          9.66074131e-03,  3.24375361e-01,  4.08756128e-03, -1.13110125e+00,
          3.16356495e-02,  2.18859464e-01,  4.23463248e-03, -4.43772376e-01,
         -3.53564732e-02, -1.21042272e-03, -8.13999772e-01,  8.93715501e-01,
         -1.05652428e+00, -5.34357846e-01,  2.01776728e-01, -6.90863967e-01,
         -3.21713537e-01, -8.10385764e-01, -1.92579731e-01,  2.11171895e-01,
          1.36302814e-01,  1.91532783e-02,  9.99080539e-01, -4.88758296e-01,
         -1.10528624e+00,  2.12251258e+00, -9.62982103e-02,  3.51776868e-01,
         -1.24361181e+00, -4.18260843e-01,  1.20783794e+00,  8.31083208e-02,
          6.90013826e-01,  1.37471807e+00], dtype=float32),
  'OPC': array([ 6.2149471e-01,  3.2993451e-02, -8.0044401e-01, -2.9904084e-02,
          3.7124997e-01,  5.6705719e-01, -1.2978039e+00,  5.9429032e-01,
         -3.9018668e-02, -7.5832933e-01, -1.5707073e+00,  5.5723749e-02,
          7.6725096e-01,  2.1462010e-02, -8.4425557e-01, -3.3608541e-01,
         -1.1982783e-03, -2.0526461e-01, -7.9022938e-01, -6.0111132e-02,
          4.7960946e-01,  3.6553192e-01,  9.6715633e-03, -6.4776272e-01,
         -3.6780444e-01, -1.2975988e-03, -4.0017635e-01,  6.3056983e-02,
          3.9700559e-01,  8.9066398e-01, -1.5127467e-01, -4.5137170e-01,
         -1.1006852e+00,  9.2994615e-02,  9.6445411e-02, -6.4482570e-01,
         -4.4846776e-01,  6.3902235e-01,  1.2585917e+00,  5.3783916e-02,
         -4.1514927e-01,  2.2972769e-01, -1.6644002e-01,  2.0504428e-01,
         -1.9461596e+00, -9.4174558e-01, -3.3963555e-01,  8.1270909e-01,
          2.5352988e-01, -6.9208670e-01], dtype=float32),
  'PC': array([-5.6497365e-02, -2.0824850e-02, -1.0605917e+00, -1.3358673e-02,
         -2.3017699e-02, -9.6217796e-02, -4.5144248e-01,  7.4911177e-01,
          2.7855554e-01, -2.1314040e-02, -9.1113871e-01,  6.2037658e-02,
         -1.5538491e-01,  1.2558940e-02,  6.6346699e-01, -9.3338704e-01,
         -7.4621509e-03, -1.1339492e+00, -3.4470919e-01,  1.1959358e+00,
         -3.9629486e-01,  3.9636612e-01,  1.7048616e-03, -9.6601427e-01,
          4.1200966e-01, -9.3462616e-03, -7.1901774e-01,  3.8207906e-01,
         -6.7712063e-01,  8.7451571e-01,  4.1887511e-02, -3.9956188e-01,
         -2.4084924e-01, -1.4261237e+00,  8.0465370e-01,  2.6933184e-01,
         -4.4396356e-01,  6.5484476e-01,  6.8694644e-02, -3.4374395e-01,
         -6.7309338e-01, -3.1737465e-01, -1.4573762e-01,  3.5355706e-02,
         -5.5670595e-01,  7.1626681e-01,  4.5796213e-01,  2.0239924e-01,
         -1.6578361e-01,  2.2113817e+00], dtype=float32),

In [22]:
# borzoi_online_dataset.dataset_mode

In [23]:
(train_folds, valid_folds, test_folds, train_regions, valid_regions, test_regions) = borzoi_online_dataset.get_train_valid_test(fold=0)

In [24]:
train_regions

,Chromosome,Start,End,Name,Original_Name,fold
0,chr1,155957121,156481409,chr1:155957121-156481409,13844,2
1,chr1,152760876,153285164,chr1:152760876-153285164,13856,2
2,chr1,152121627,152645915,chr1:152121627-152645915,13912,2
3,chr1,150548091,151072379,chr1:150548091-151072379,13942,2
4,chr1,150351399,150875687,chr1:150351399-150875687,13956,2
...,...,...,...,...,...,...
39798,chrX,4650488,5174776,chrX:4650488-5174776,54865,7
39799,chrX,36285423,36809711,chrX:36285423-36809711,54879,7
39800,chrX,4847180,5371468,chrX:4847180-5371468,55180,7
39801,chrX,4355450,4879738,chrX:4355450-4879738,55197,7
39802,chrX,36531288,37055576,chrX:36531288-37055576,55415,7

In [25]:
loader1 = borzoi_online_dataset.get_dataloader(folds=0, region_bed=train_regions)

In [26]:
borzoi_online_dataset.bed

,Chromosome,Start,End,region,Original_Name,fold
0,chr1,155957121,156481409,chr1:155957121-156481409,13844,2
1,chr1,152760876,153285164,chr1:152760876-153285164,13856,2
2,chr1,152121627,152645915,chr1:152121627-152645915,13912,2
3,chr1,150548091,151072379,chr1:150548091-151072379,13942,2
4,chr1,150351399,150875687,chr1:150351399-150875687,13956,2
...,...,...,...,...,...,...
39798,chrX,4650488,5174776,chrX:4650488-5174776,54865,7
39799,chrX,36285423,36809711,chrX:36285423-36809711,54879,7
39800,chrX,4847180,5371468,chrX:4847180-5371468,55180,7
39801,chrX,4355450,4879738,chrX:4355450-4879738,55197,7
39802,chrX,36531288,37055576,chrX:36531288-37055576,55415,7

In [27]:
loader2 = borzoi_online_dataset.get_dataloader(folds=0, region_bed=test_regions)

In [28]:
borzoi_online_dataset.bed

,Chromosome,Start,End,region,Original_Name,fold
0,chr1,236570394,237094682,chr1:236570394-237094682,7148,1
1,chr1,238242276,238766564,chr1:238242276-238766564,7196,1
2,chr1,243307095,243831383,chr1:243307095-243831383,7247,1
3,chr1,245274015,245798303,chr1:245274015-245798303,7268,1
4,chr1,238340622,238864910,chr1:238340622-238864910,7332,1
...,...,...,...,...,...,...
6329,chrX,118890376,119414664,chrX:118890376-119414664,13775,1
6330,chrX,118644511,119168799,chrX:118644511-119168799,13776,1
6331,chrX,122142385,122666673,chrX:122142385-122666673,13784,1
6332,chrX,128633221,129157509,chrX:128633221-129157509,13788,1
6333,chrX,124551862,125076150,chrX:124551862-125076150,13801,1

In [29]:
borzoi_online_dataset.bed

,Chromosome,Start,End,region,Original_Name,fold
0,chr1,236570394,237094682,chr1:236570394-237094682,7148,1
1,chr1,238242276,238766564,chr1:238242276-238766564,7196,1
2,chr1,243307095,243831383,chr1:243307095-243831383,7247,1
3,chr1,245274015,245798303,chr1:245274015-245798303,7268,1
4,chr1,238340622,238864910,chr1:238340622-238864910,7332,1
...,...,...,...,...,...,...
6329,chrX,118890376,119414664,chrX:118890376-119414664,13775,1
6330,chrX,118644511,119168799,chrX:118644511-119168799,13776,1
6331,chrX,122142385,122666673,chrX:122142385-122666673,13784,1
6332,chrX,128633221,129157509,chrX:128633221-129157509,13788,1
6333,chrX,124551862,125076150,chrX:124551862-125076150,13801,1

In [30]:
borzoi_online_dataset.bed[ borzoi_online_dataset.bed["Original_Name" ] == 7148]

,Chromosome,Start,End,region,Original_Name,fold
0,chr1,236570394,237094682,chr1:236570394-237094682,7148,1

In [31]:
# counter=  0
# for batch in loader1:
#     counter += 1
#     pass

# print(f'counter: {counter}')
# print('printing batch items...')
# for k, v in batch.items():
#     print(k, v.dtype, v.shape)
# # del loader1

In [32]:
# batch.items()

In [33]:
for idx, batch in enumerate(loader2):
    X = batch["dna_one_hot"]
    embedding = batch.get("cell_type_embedding", None)
    y_true = batch["bw_values"]
    break

print(X, X.shape)
print(embedding, embedding.shape)
print(y_true, y_true.shape)

/home/tlgallent/miniconda/envs/bolero_dev/lib/python3.10/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
2024-10-24 14:09:06,329	INFO streaming_executor.py:108 -- Starting execution of Dataset. Full logs are in /tmp/ray/session_2024-10-24_14-08-28_775293_437424/logs/ray-data
2024-10-24 14:09:06,329	INFO streaming_executor.py:109 -- Execution plan of Dataset: InputDataBuffer[Input] -> AllToAllOperator[Repartition]

Loading genome DNA one-hot encoding...
Created remote one-hot object at ObjectRef(00ffffffffffffffffffffffffffffffffffffff0100000002e1f505)
Data loader kwargs {'batch_size': 2, 'prefetch_batches': 3, 'drop_last': True}

2024-10-24 14:09:39,427	INFO streaming_executor.py:108 -- Starting execution of Dataset. Full logs are in /tmp/ray/session_2024-10-24_14-08-28_775293_437424/logs/ray-data
2024-10-24 14:09:39,427	INFO streaming_executor.py:109 -- Execution plan of Dataset: InputDataBuffer[Input] -> ActorPoolMapOperator[MapBatches(select_columns)->MapBatches(FetchRegionBigWigsReduced)] -> ActorPoolMapOperator[MapBatches(FetchRegionBigWigsReduced)] -> ActorPoolMapOperator[MapBatches(FetchRegionBigWigsReduced)] -> ActorPoolMapOperator[MapBatches(_concat_bw_chunks)->MapBatches(FetchRegionOneHot)] -> TaskPoolMapOperator[MapBatches(ReverseComplement)->MapBatches(_region_to_global_coords)] -> TaskPoolMapOperator[FlatMap(_convert_data)]

tensor([[[False, False, False,  ..., False, False,  True],
         [False, False,  True,  ...,  True,  True, False],
         [False, False, False,  ..., False, False, False],
         [ True,  True, False,  ..., False, False, False]],

        [[False, False, False,  ..., False, False,  True],
         [False, False,  True,  ...,  True,  True, False],
         [False, False, False,  ..., False, False, False],
         [ True,  True, False,  ..., False, False, False]]]) torch.Size([2, 4, 524288])
tensor([[-6.9326e-01,  2.4377e-02,  5.1223e-01, -1.1037e-01,  3.2104e-01,
          4.9961e-02, -5.9708e-01,  5.6469e-01, -1.5926e-01, -2.8574e-01,
          2.7541e-01,  6.6600e-01,  2.1080e-01,  1.9472e-02, -6.7125e-02,
         -1.6400e-01,  9.9672e-03, -1.0936e+00, -5.4624e-01, -1.3277e+00,
          7.5367e-02,  1.8270e-01,  2.4486e-03, -5.2664e-01, -1.2295e+00,
          2.4672e-04, -1.0414e+00, -2.0426e-01,  2.9266e-01, -8.8553e-01,
          1.1628e-01,  1.7349e-01, -4.5958e-02, -1.2414e+00,  9.6094e-01,
          8.2925e-02, -7.5481e-01,  1.0932e+00,  9.4722e-01,  2.9877e-01,
          4.4456e-01, -1.9631e-01,  4.7793e-02,  5.6545e-01,  3.5394e-01,
         -9.1683e-01, -6.7716e-01, -8.1293e-01,  2.1437e-01, -6.2599e-01],
        [-5.7615e-01,  3.7418e-02, -4.5103e-01, -1.1325e-01,  1.7380e-01,
         -1.3753e-01,  8.2729e-01, -5.8024e-01, -2.3396e-01, -7.5282e-01,
          4.6750e-01, -1.7818e-01, -1.6687e-01,  9.3818e-03,  4.5087e-01,
         -6.4138e-02, -2.0131e-02,  2.0074e-01, -1.4204e-01,  4.3764e-02,
          6.1469e-01, -1.4207e-01, -3.1790e-03, -2.4537e-01, -5.3263e-01,
         -5.8811e-03,  1.2103e+00, -7.6166e-01, -1.0350e+00, -2.8327e-01,
          4.0420e-01, -1.1169e-01, -1.9188e-01,  3.6048e-02,  7.0418e-01,
         -2.2855e-01, -3.6034e-01,  4.9301e-01, -6.0056e-01,  4.3848e-01,
          1.6229e+00, -6.1474e-01, -2.9257e-01,  2.3380e-01, -8.7168e-02,
          2.1964e-01,  7.8487e-01, -3.7588e-01,  1.1585e-01, -1.1753e+00]]) torch.Size([2, 50])
tensor([[0.0312, 0.0000, 0.0312,  ..., 0.0625, 0.1250, 0.0625],
        [0.0000, 0.0000, 0.0312,  ..., 0.0000, 0.0000, 0.0000]]) torch.Size([2, 16384])

In [ ]:
for k, v in b.items():
    print(k, v.dtype, v.shape)
# del loader1

In [32]:
from bolero import Genome
genome = Genome('hg38')
genome.parse_global_coords(b['region'].cpu().numpy())

  Chromosome      Start        End                      Name
0       chr1  149859669  150383957  chr1:149859669-150383957
1       chr1  154973661  155497949  chr1:154973661-155497949

In [42]:
region_index =1 #needs to be 0 or 1
cell_type = next((k for k, v in leg_map.items() if v == b['cell_type_id'][region_index]), None)
print(f'cell type: {cell_type}')
atac_bw_path = borzoi_online_dataset.bigwig_names_dict[cell_type]
print(atac_bw_path)
chrom = "chr1"
start = "154973661"
end = "155497949"

cell type: ASC
/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/ASC.bw

In [43]:
import pyBigWig
print(atac_bw_path)
with pyBigWig.open(atac_bw_path) as bw:
    data = np.nan_to_num(bw.values(chrom, int(start), int(end), numpy=True))

data[:129]

/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/ASC.bw

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,  0.,  1.,  0.,
        3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  1.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,
        0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  5.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,
        4.,  0.,  3.,  0.,  0.,  0.,  2.,  0.,  0.,  3.,  3.,  1.,  1.,
        0.,  2.,  0.,  3.,  2.,  1.,  8.,  9.,  1.,  0.,  0.,  0.,  0.,
        0.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  0., 14.,  0.,  3.],
      dtype=float32)

In [44]:
b['bw_values'][region_index,:4]

tensor([0.2188, 0.2812, 0.3125, 1.6562])

In [45]:
for i in range(4):
    print(sum(data[i*32:i*32 + 32])/32)

0.21875
0.28125
0.3125
1.65625

In [37]:
b['dna_one_hot'][region_index,:,:16]

tensor([[ True, False, False,  True,  True,  True,  True, False, False,  True,
         False,  True,  True, False, False, False],
        [False, False, False, False, False, False, False, False,  True, False,
         False, False, False, False,  True,  True],
        [False,  True, False, False, False, False, False, False, False, False,
         False, False, False,  True, False, False],
        [False, False,  True, False, False, False, False,  True, False, False,
          True, False, False, False, False, False]])

In [38]:
s = int(start)
e_small = s+16
e = int(end)
e_small

149859685

In [39]:
import torch
nucleotides = np.array(['A', 'C', 'G', 'T'])

for i in range(16):
    indices = torch.argmax(b['dna_one_hot'][1,:,i].int())
    nucleotide = nucleotides[indices.item()]
    print(f"nucleotide: {nucleotide}\n")

nucleotide: G

nucleotide: A

nucleotide: G

nucleotide: A

nucleotide: A

nucleotide: A

nucleotide: G

nucleotide: G

nucleotide: A

nucleotide: C

nucleotide: A

nucleotide: G

nucleotide: G

nucleotide: A

nucleotide: A

nucleotide: A

In [40]:
# data_key = ('bw_values')
# keys = ['Original_Name', 'bw_values', 'dna_one_hot', 'region']

# for k in keys:
#     print(k)
#     if k not in data_key:
#         print('true')
#     else:
#         print('false')

In [41]:
batch['cell_type_id']

NameError: name 'batch' is not defined

In [ ]:
batch['bw_values'][0]

## CHECK REGIONS AND DNA ONE HOT MANUAL ##

In [ ]:
list(reversed(sorted(list(batch['bw_values'][1,0,:]))))[:15]

In [ ]:
batch['bw_values'][0,:,:6]

In [ ]:
batch['dna_one_hot'][1,:,:322]

In [ ]:
batch['Original_Name'][0]

In [ ]:
batch['Original_Name'][1]

In [ ]:
batch['region'][1]

In [ ]:
batch['region'][0]

In [ ]:
from bolero import Genome

In [ ]:
genome = Genome('hg38')

In [ ]:
genome.parse_global_coords(batch['region'].cpu().numpy())

In [ ]:
#region 0
train_regions[train_regions['Original_Name'] == 52596]

In [ ]:
#region 1
train_regions[train_regions['Original_Name'] == 52883]

In [ ]:
borzoi_online_dataset.bigwig_names_dict

In [ ]:
atac_bw_path = borzoi_online_dataset.bigwig_names_dict['ASC']
chrom = "chrX"
start = "36432942"
end = "36957230"

In [ ]:
import pyBigWig
with pyBigWig.open(atac_bw_path) as bw:
    data = np.nan_to_num(bw.values(chrom, int(start), int(end), numpy=True))

data[:129]

In [ ]:
batch['bw_values'][0,0,:4]

In [ ]:
for i in range(4):
    print(sum(data[i*32:i*32 + 32])/32)

In [ ]:
atac_bw_path = borzoi_online_dataset.bigwig_names_dict['Vip']
# chrom = "chrX"
# start = "36432942"
# end = "36957230"

In [ ]:
import pyBigWig
with pyBigWig.open(atac_bw_path) as bw:
    data = np.nan_to_num(bw.values(chrom, int(start), int(end), numpy=True))

data[:129]

In [ ]:
batch['bw_values'][0,1,:4]

In [ ]:
for i in range(4):
    print(sum(data[i*32:i*32 + 32])/32)

## CHECK REVERSE COMPLEMENT MANUAL ##

In [ ]:
for k, v in batch.items():
    print(k, v.dtype, v.shape)

In [ ]:
batch['dna_one_hot'][0,:,:16]

In [ ]:
s = int(start)
e_small = s+16
e = int(end)
e_small

In [ ]:
import torch
nucleotides = np.array(['A', 'C', 'G', 'T'])

for i in range(16):
    indices = torch.argmax(batch['dna_one_hot'][0,:,i].int())
    nucleotide = nucleotides[indices.item()]
    print(f"nucleotide: {nucleotide}\n")

In [ ]:
batch['dna_one_hot'][0,:,1]

In [ ]:
batch['dna_one_hot'][0,:,2]

In [ ]:
batch['dna_one_hot'][0,:,3]

In [ ]:
batch['dna_one_hot'][0,:,4]

In [ ]:
batch['dna_one_hot'][0,:,4]

## TESTING FINETUNE SCRIPT

In [ ]:
import joblib
import numpy as np
import pandas as pd
import torch
from bolero import init
from bolero.tl.model.borzoi.train import BorzoiLoRATrainer
import anndata
import time
from datetime import datetime
import os



def main(config):

    # init(num_cpus=16, object_store_memory_gb=100, verbose=True)
    init(num_cpus=32, verbose=True)   
    print(torch.version.cuda)
    print(torch.__version__)
    print(f'Is CUDA available? {torch.cuda.is_available()}')
    

    
    config = BorzoiLoRATrainer.make_config(**config)
    trainer = BorzoiLoRATrainer(config)
    # breakpoint()
    trainer.train(skip_output_adjust=True)

if __name__ == '__main__':

    
    # use_kv_bottleneck = 1
    use_kv_bottleneck = 0
    use_ema = 0
    context_out = 1
    n_pseudobulks = 2
    fold_id = 0
    lora_preset = "all_conditional"

    # kv_bottleneck = "local"
    kv_bottleneck = None
    n_cycles = 1
    cov_soft_clamp = None
    loss_total_weight = 0.2

    warmup_steps = 10000
    lr = 5e-5
    train_batches = 5000
    val_batches = 1000

    # for quick test
    # warmup_steps = 100
    # lr = 1e-3
    # train_batches = 2000
    # val_batches = 500
    
    name = "testing_loader"
    data_dir = '/large_storage/zhoulab/tlgallent/data/Li2023Science/'
    fold_id = 0
    # num_cell_types_used = 30

    bigwig_dir = os.path.join(data_dir, "bigwig")
    # all_entries = os.listdir(bigwig_dir)
    # bw_files = [entry for entry in all_entries if entry.lower().endswith(".bw")]
    # if len(bw_files) < num_cell_types_used:
    #     print(
    #         f"Warning: Only {len(bw_files)} BigWig (.bw) files found, "
    #         f"but {num_cell_types_used} are required."
    #     )
    # selected_bw_files = bw_files[:num_cell_types_used]

    
    
    cell_types = [
    'ASC', 'Amy', 'CHD7', 'EC', 'Foxp2', 'L4_IT', 'L5_ET',
    'L5_IT', 'L6_CT', 'L6_IT', 'L6_IT_Car3', 'L6b', 'L23_IT',
    'L56_NP', 'Lamp5', 'Lamp5_LHX6', 'MGC', 'MSN_D1', 'MSN_D2',
    'ODC', 'OPC', 'PC', 'Pvalb', 'Pvalb_ChC', 'Sncg', 'Sst',
    'SubCtx', 'VLMC', 'Vip'
    ]
    expected_total_length = len(cell_types)

    leave_out = True

    if leave_out:
        
        cell_types = [
            'ASC', 'Amy', 'CHD7', 'EC', 'Foxp2', 'L4_IT', 'L5_ET',
            'L5_IT', 'L6_IT_Car3', 'L6b', 'L23_IT',
            'L56_NP', 'Lamp5', 'Lamp5_LHX6', 'MSN_D1', 'MSN_D2',
            'ODC', 'PC', 'Pvalb', 'Pvalb_ChC', 'Sncg',
            'SubCtx', 'VLMC', 'Vip'
            ]
        
        left_out = ['L6_IT', 'L6_CT', 'Sst', 'OPC', 'MGC']


        overlap = set(cell_types) & set(left_out)
        
        total_length = len(cell_types) + len(left_out)
        assert total_length == expected_total_length, (
        f"Total length is {total_length}, expected {expected_total_length}."
    )
        assert not overlap, f"Overlap found between lists: {overlap}"


    bw_paths_enumerated = [os.path.join(bigwig_dir, file) + '.bw' for file in cell_types]

    assert len(cell_types) == len(bw_paths_enumerated), "num cell types must be same length as paths enuemrated"
    print(f'Using {len(cell_types)} cell types: {bw_paths_enumerated}')

    checkpoint_path = f"/large_storage/zhoulab/hanliu/240729-WMBRNAModel/05.borzoi/borzoi_pretrain/torch_checkpoints/borzoi.human.f{fold_id}.pt"
    dataset_path = (
        f"{data_dir}"
    )
    vq_records_path = "/home/hanliu/data/240729-WMBRNAModel/02.scVI/scVI-VQ/ALL_vq/vq_records.target_frags_8000000.joblib"
    emb_input_features = 50
    use_ema = False if use_ema == 0 else True
    context_out = False if context_out == 0 else True

    config = {
        # file path and wandb
        "output_dir": "model",
        "savename": name,
        "wandb_project": "borzoi_finetuning",
        "wandb_job_type": "lora",
        "wandb_name": f"{name}-fold-{fold_id}",
        # train
        "start_early_stop_after_epoch": 15,
        "max_epochs": 30,
        "patience": 10,
        "use_amp": True,
        "use_ema": use_ema,
        "train_batches": train_batches,
        "val_batches": val_batches,
        "batch_size": 2,
        "accumulate_grad": 64,
        "lr": lr,
        "warmup_steps": warmup_steps,
        "weight_decay": 1e-8,
        "global_clipnorm": 0.1,
        # dataset
        # "dataset_path": dataset_path,
        "fold_split_id": 0,
        "shuffle_rows": 300,
        "dna_window": 524288,
        "pos_resolution": 32,
        "reverse_complement": True,
        "max_jitter": 3,
        # "n_pseudobulks": n_pseudobulks,
        # LoRA Model
        "base_checkpoint_path": checkpoint_path,
        "emb_input_features": emb_input_features,
        "out_channels": 1,
        "hidden_dim": 256,
        "hidden_layers": 1,
        "output_layer_groups": 4,
        "lora_dropout": 0.01,
        "loss_total_weight": loss_total_weight,
        "lora_preset": lora_preset,
        "context_output": context_out,
        # "lora_norm": "layer",
        # base model dropout:
        "transformer_attn_dropout": 0.0,
        "transformer_pos_dropout": 0.0,
        "transformer_ff_dropout": 0.0,
        "final_conv_dropout": 0.0,
        "final_output_dropout": 0.01,
        # pseudobulk and embedding
        # "vq_records": vq_records_path,
        # "target_cov": 8e6,
        # "use_vq_emb": not use_kv_bottleneck,
        "kv_bottleneck": kv_bottleneck,
        "num_memories": 256,
        "dim_memory": 20,
        "num_memory_codebooks": 2,
        "additional_embs": 1,
        "n_cycles": n_cycles,
        # "cov_soft_clamp": cov_soft_clamp,
        #Online Loader reqs
        'bigwig_paths': bw_paths_enumerated,
        'bed': None,
        'embeddings_path': '/large_storage/zhoulab/tlgallent/data/cell_29000_rna_raw_gencode_adata_with_embeddings.h5ad',
        'lora': True,
        # 'use_borzoi_regions': True,
    }


    main(config)

2024-10-24 15:14:22,912	INFO worker.py:1604 -- Calling ray.init() again after it has already been called.

Using 24 cell types: ['/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/ASC.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/Amy.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/CHD7.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/EC.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/Foxp2.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/L4_IT.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/L5_ET.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/L5_IT.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/L6_IT_Car3.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/L6b.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/L23_IT.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/L56_NP.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/Lamp5.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/Lamp5_LHX6.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/MSN_D1.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/MSN_D2.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/ODC.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/PC.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/Pvalb.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/Pvalb_ChC.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/Sncg.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/SubCtx.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/VLMC.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/Vip.bw']
Enabled torch cudnn
Disabled ray lineage reconstruction and task retries
12.1
2.4.1
Is CUDA available? False
Create BorzoiDatasetOnline with config: {'bigwig_paths': ['/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/ASC.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/Amy.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/CHD7.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/EC.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/Foxp2.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/L4_IT.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/L5_ET.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/L5_IT.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/L6_IT_Car3.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/L6b.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/L23_IT.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/L56_NP.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/Lamp5.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/Lamp5_LHX6.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/MSN_D1.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/MSN_D2.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/ODC.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/PC.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/Pvalb.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/Pvalb_ChC.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/Sncg.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/SubCtx.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/VLMC.bw', '/large_storage/zhoulab/tlgallent/data/Li2023Science/bigwig/Vip.bw'], 'bed': None, 'embeddings_path': '/large_storage/zhoulab/tlgallent/data/cell_29000_rna_raw_gencode_adata_with_embeddings.h5ad', 'lora': True, 'genome': 'hg38', 'batch_size': 2, 'dna_window': 524288, 'pos_resolution': 32, 'reverse_complement': True, 'max_jitter': 3, 'clamp_sqrt_threshold': None, 'shuffle_files': True, 'use_borzoi_regions': True}

wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: tlg (tlg-arc-institute). Use `wandb login --relogin` to force relogin

==========================
Training output layer only
==========================
Setting up model from config
Loading base model weights from: /large_storage/zhoulab/hanliu/240729-WMBRNAModel/05.borzoi/borzoi_pretrain/torch_checkpoints/borzoi.human.f0.pt
Total model parameters 195429893, trainable parameters 24157925
EMA is not used.
===================
Training LoRA model
===================

2024-10-24 15:14:51,441	INFO streaming_executor.py:108 -- Starting execution of Dataset. Full logs are in /tmp/ray/session_2024-10-24_14-08-28_775293_437424/logs/ray-data
2024-10-24 15:14:51,442	INFO streaming_executor.py:109 -- Execution plan of Dataset: InputDataBuffer[Input] -> AllToAllOperator[Repartition]

============================================================================================================================================
Layer (type (var_name))                                           Input Shape               Output Shape              Param #
============================================================================================================================================
BorzoiLoRA (BorzoiLoRA)                                           --                        [1, 1, 16352]             --
├─ConvDna (conv_dna)                                              [1, 4, 524288]            [1, 512, 262144]          --
│    └─ConditionalLoRAConv (conv_layer)                           [1, 4, 524288]            [1, 512, 524288]          31,232
│    │    └─EmbeddingMLP (lora_A_module)                          --                        [1, 45, 60]               255,373
│    │    └─EmbeddingMLP (lora_B_module)                          --                        [1, 512, 45]              1,577,473
│    └─MaxPool1d (max_pool)                                       [1, 512, 524288]          [1, 512, 262144]          --
├─SequentialwithArgs (res_tower)                                  [1, 512, 262144]          [1, 1280, 16384]          --
│    └─ConvBlock (0)                                              [1, 512, 262144]          [1, 608, 262144]          --
│    │    └─BatchNorm1d (norm)                                    [1, 512, 262144]          [1, 512, 262144]          (1,024)
│    │    └─GELU (activation)                                     [1, 512, 262144]          [1, 512, 262144]          --
│    │    └─ConditionalLoRAConv (conv_layer)                      [1, 512, 262144]          [1, 608, 262144]          10,983,234
│    └─MaxPool1d (1)                                              [1, 608, 262144]          [1, 608, 131072]          --
│    └─ConvBlock (2)                                              [1, 608, 131072]          [1, 736, 131072]          --
│    │    └─BatchNorm1d (norm)                                    [1, 608, 131072]          [1, 608, 131072]          (1,216)
│    │    └─GELU (activation)                                     [1, 608, 131072]          [1, 608, 131072]          --
│    │    └─ConditionalLoRAConv (conv_layer)                      [1, 608, 131072]          [1, 736, 131072]          13,442,722
│    └─MaxPool1d (3)                                              [1, 736, 131072]          [1, 736, 65536]           --
│    └─ConvBlock (4)                                              [1, 736, 65536]           [1, 896, 65536]           --
│    │    └─BatchNorm1d (norm)                                    [1, 736, 65536]           [1, 736, 65536]           (1,472)
│    │    └─GELU (activation)                                     [1, 736, 65536]           [1, 736, 65536]           --
│    │    └─ConditionalLoRAConv (conv_layer)                      [1, 736, 65536]           [1, 896, 65536]           16,842,722
│    └─MaxPool1d (5)                                              [1, 896, 65536]           [1, 896, 32768]           --
│    └─ConvBlock (6)                                              [1, 896, 32768]           [1, 1056, 32768]          --
│    │    └─BatchNorm1d (norm)                                    [1, 896, 32768]           [1, 896, 32768]           (1,792)
│    │    └─GELU (activation)                                     [1, 896, 32768]           [1, 896, 32768]           --
│    │    └─ConditionalLoRAConv (conv_layer)                      [1, 896, 32768]           [1, 1056, 32768]          21,084,482
│    └─MaxPool1d (7)                                              [1, 1056, 32768]          [1, 1056, 16384]          --
│    └─ConvBlock (8)                                              [1, 1056, 16384]          [1, 1280, 16384]          --
│    │    └─BatchNorm1d (norm)                                    [1, 1056, 16384]          [1, 1056, 16384]          (2,112)
│    │    └─GELU (activation)                                     [1, 1056, 16384]          [1, 1056, 16384]          --
│    │    └─ConditionalLoRAConv (conv_layer)                      [1, 1056, 16384]          [1, 1280, 16384]          26,107,426
├─SequentialwithArgs (unet1)                                      [1, 1280, 16384]          [1, 1536, 8192]           --
│    └─MaxPool1d (0)                                              [1, 1280, 16384]          [1, 1280, 8192]           --
│    └─ConvBlock (1)                                              [1, 1280, 8192]           [1, 1536, 8192]           --
│    │    └─BatchNorm1d (norm)                                    [1, 1280, 8192]           [1, 1280, 8192]           (2,560)
│    │    └─GELU (activation)                                     [1, 1280, 8192]           [1, 1280, 8192]           --
│    │    └─ConditionalLoRAConv (conv_layer)                      [1, 1280, 8192]           [1, 1536, 8192]           33,204,482
├─MaxPool1d (_max_pool)                                           [1, 1536, 8192]           [1, 1536, 4096]           --
├─ConvBlock (horizontal_conv0)                                    [1, 1280, 16384]          [1, 1536, 16384]          --
│    └─BatchNorm1d (norm)                                         [1, 1280, 16384]          [1, 1280, 16384]          (2,560)
│    └─GELU (activation)                                          [1, 1280, 16384]          [1, 1280, 16384]          --
│    └─ConditionalLoRAConv (conv_layer)                           [1, 1280, 16384]          [1, 1536, 16384]          1,967,616
│    │    └─EmbeddingMLP (lora_A_module)                          --                        [1, 15, 1280]             1,327,873
│    │    └─EmbeddingMLP (lora_B_module)                          --                        [1, 1536, 15]             1,577,473
├─ConvBlock (horizontal_conv1)                                    [1, 1536, 8192]           [1, 1536, 8192]           --
│    └─BatchNorm1d (norm)                                         [1, 1536, 8192]           [1, 1536, 8192]           (3,072)
│    └─GELU (activation)                                          [1, 1536, 8192]           [1, 1536, 8192]           --
│    └─ConditionalLoRAConv (conv_layer)                           [1, 1536, 8192]           [1, 1536, 8192]           2,360,832
│    │    └─EmbeddingMLP (lora_A_module)                          --                        [1, 15, 1536]             1,577,473
│    │    └─EmbeddingMLP (lora_B_module)                          --                        [1, 1536, 15]             1,577,473
├─SequentialwithArgs (transformer)                                [1, 4096, 1536]           [1, 4096, 1536]           --
│    └─TransformerLayer (0)                                       [1, 4096, 1536]           [1, 4096, 1536]           --
│    │    └─SequentialwithArgs (layers)                           [1, 4096, 1536]           [1, 4096, 1536]           25,225,188
│    └─TransformerLayer (1)                                       [1, 4096, 1536]           [1, 4096, 1536]           --
│    │    └─SequentialwithArgs (layers)                           [1, 4096, 1536]           [1, 4096, 1536]           25,225,188
│    └─TransformerLayer (2)                                       [1, 4096, 1536]           [1, 4096, 1536]           --
│    │    └─SequentialwithArgs (layers)                           [1, 4096, 1536]           [1, 4096, 1536]           25,225,188
│    └─TransformerLayer (3)                                       [1, 4096, 1536]           [1, 4096, 1536]           --
│    │    └─SequentialwithArgs (layers)                           [1, 4096, 1536]           [1, 4096, 1536]           25,225,188
│    └─TransformerLayer (4)                                       [1, 4096, 1536]           [1, 4096, 1536]           --
│    │    └─SequentialwithArgs (layers)                           [1, 4096, 1536]           [1, 4096, 1536]           25,225,188
│    └─TransformerLayer (5)                                       [1, 4096, 1536]           [1, 4096, 1536]           --
│    │    └─SequentialwithArgs (layers)                           [1, 4096, 1536]           [1, 4096, 1536]           25,225,188
│    └─TransformerLayer (6)                                       [1, 4096, 1536]           [1, 4096, 1536]           --
│    │    └─SequentialwithArgs (layers)                           [1, 4096, 1536]           [1, 4096, 1536]           25,225,188
│    └─TransformerLayer (7)                                       [1, 4096, 1536]           [1, 4096, 1536]           --
│    │    └─SequentialwithArgs (layers)                           [1, 4096, 1536]           [1, 4096, 1536]           25,225,188
├─SequentialwithArgs (upsampling_unet1)                           [1, 1536, 4096]           [1, 1536, 8192]           --
│    └─ConvBlock (0)                                              [1, 1536, 4096]           [1, 1536, 4096]           --
│    │    └─BatchNorm1d (norm)                                    [1, 1536, 4096]           [1, 1536, 4096]           (3,072)
│    │    └─GELU (activation)                                     [1, 1536, 4096]           [1, 1536, 4096]           --
│    │    └─ConditionalLoRAConv (conv_layer)                      [1, 1536, 4096]           [1, 1536, 4096]           5,515,778
│    └─Upsample (1)                                               [1, 1536, 4096]           [1, 1536, 8192]           --
├─ConvBlock (separable1)                                          [1, 1536, 8192]           [1, 1536, 8192]           --
│    └─Identity (norm)                                            [1, 1536, 8192]           [1, 1536, 8192]           --
│    └─Identity (activation)                                      [1, 1536, 8192]           [1, 1536, 8192]           --
│    └─Sequential (conv_layer)                                    --                        --                        --
│    │    └─ConditionalLoRAConv (0)                               [1, 1536, 8192]           [1, 1536, 8192]           4,665,994
│    │    └─ConditionalLoRAConv (1)                               [1, 1536, 8192]           [1, 1536, 8192]           5,515,778
├─SequentialwithArgs (upsampling_unet0)                           [1, 1536, 8192]           [1, 1536, 16384]          --
│    └─ConvBlock (0)                                              [1, 1536, 8192]           [1, 1536, 8192]           --
│    │    └─BatchNorm1d (norm)                                    [1, 1536, 8192]           [1, 1536, 8192]           (3,072)
│    │    └─GELU (activation)                                     [1, 1536, 8192]           [1, 1536, 8192]           --
│    │    └─ConditionalLoRAConv (conv_layer)                      [1, 1536, 8192]           [1, 1536, 8192]           5,515,778
│    └─Upsample (1)                                               [1, 1536, 8192]           [1, 1536, 16384]          --
├─ConvBlock (separable0)                                          [1, 1536, 16384]          [1, 1536, 16384]          --
│    └─Identity (norm)                                            [1, 1536, 16384]          [1, 1536, 16384]          --
│    └─Identity (activation)                                      [1, 1536, 16384]          [1, 1536, 16384]          --
│    └─Sequential (conv_layer)                                    --                        --                        --
│    │    └─ConditionalLoRAConv (0)                               [1, 1536, 16384]          [1, 1536, 16384]          4,665,994
│    │    └─ConditionalLoRAConv (1)                               [1, 1536, 16384]          [1, 1536, 16384]          5,515,778
├─SequentialwithArgs (final_joined_convs)                         [1, 1536, 16384]          [1, 1920, 16384]          --
│    └─ConvBlock (0)                                              [1, 1536, 16384]          [1, 1920, 16384]          --
│    │    └─BatchNorm1d (norm)                                    [1, 1536, 16384]          [1, 1536, 16384]          (3,072)
│    │    └─GELU (activation)                                     [1, 1536, 16384]          [1, 1536, 16384]          --
│    │    └─ConditionalLoRAConv (conv_layer)                      [1, 1536, 16384]          [1, 1920, 16384]          6,480,386
│    └─Dropout (1)                                                [1, 1920, 16384]          [1, 1920, 16384]          --
│    └─GELU (2)                                                   [1, 1920, 16384]          [1, 1920, 16384]          --
├─TargetLengthCrop (crop)                                         [1, 1920, 16384]          [1, 1920, 16352]          --
├─ContextOutputHead (final_output_head)                           [1, 1920, 16352]          [1, 1, 16352]             --
│    └─Residual (residual_context)                                [1, 16352, 1920]          [1, 16352, 1920]          --
│    │    └─SequentialwithArgs (fn)                               [1, 16352, 1920]          [1, 16352, 1920]          24,156,004
│    └─OutputHead (final_output_head)                             [1, 1920, 16352]          [1, 1, 16352]             --
│    │    └─Conv1d (0)                                            [1, 1920, 16352]          [1, 1, 16352]             1,921
│    │    └─Softplus (1)                                          [1, 1, 16352]             [1, 1, 16352]             --
============================================================================================================================================
Total params: 397,777,825
Trainable params: 226,572,705
Non-trainable params: 171,205,120
Total mult-adds (M): 256.70
============================================================================================================================================
Input size (MB): 8.39
Forward/backward pass size (MB): 6081.49
Params size (MB): 901.14
Estimated Total Size (MB): 6991.01
============================================================================================================================================
Total model parameters 397777825, trainable parameters 226572705
EMA is not used.
Current epoch: 1, max epochs: 30, stop flag: False.

- Repartition 1:   0%|                                                                                        …

Split Repartition 2:   0%|                                                                                    …

Running 0:   0%|                                                                                              …

Loading genome DNA one-hot encoding...

2024-10-24 15:14:57,751	INFO streaming_executor.py:108 -- Starting execution of Dataset. Full logs are in /tmp/ray/session_2024-10-24_14-08-28_775293_437424/logs/ray-data
2024-10-24 15:14:57,752	INFO streaming_executor.py:109 -- Execution plan of Dataset: InputDataBuffer[Input] -> ActorPoolMapOperator[MapBatches(select_columns)->MapBatches(FetchRegionBigWigsReduced)] -> ActorPoolMapOperator[MapBatches(FetchRegionBigWigsReduced)] -> ActorPoolMapOperator[MapBatches(FetchRegionBigWigsReduced)] -> ActorPoolMapOperator[MapBatches(FetchRegionBigWigsReduced)] -> ActorPoolMapOperator[MapBatches(FetchRegionBigWigsReduced)] -> ActorPoolMapOperator[MapBatches(FetchRegionBigWigsReduced)] -> ActorPoolMapOperator[MapBatches(_concat_bw_chunks)->MapBatches(FetchRegionOneHot)] -> TaskPoolMapOperator[MapBatches(ReverseComplement)->MapBatches(_region_to_global_coords)] -> TaskPoolMapOperator[FlatMap(_convert_data)] -> LimitOperator[limit=10002]

Created remote one-hot object at ObjectRef(00ffffffffffffffffffffffffffffffffffffff010000000ae1f505)
Data loader kwargs {'batch_size': 2, 'prefetch_batches': 3, 'drop_last': True}

- MapBatches(select_columns)->MapBatches(FetchRegionBigWigsReduced) 1:   0%|                                  …

- MapBatches(FetchRegionBigWigsReduced) 2:   0%|                                                              …

- MapBatches(FetchRegionBigWigsReduced) 3:   0%|                                                              …

- MapBatches(FetchRegionBigWigsReduced) 4:   0%|                                                              …

- MapBatches(FetchRegionBigWigsReduced) 5:   0%|                                                              …

- MapBatches(FetchRegionBigWigsReduced) 6:   0%|                                                              …

- MapBatches(_concat_bw_chunks)->MapBatches(FetchRegionOneHot) 7:   0%|                                       …

- MapBatches(ReverseComplement)->MapBatches(_region_to_global_coords) 8:   0%|                                …

- FlatMap(_convert_data) 9:   0%|                                                                             …

- limit=10002 10:   0%|                                                                                       …

Running 0:   0%|                                                                                              …